name: Sync to Hugging Face Space (Docker)

on:
  push:
    branches: [main]  # أو master
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote set-url origin https://eissa0070:$HF_TOKEN@huggingface.co/spaces/eissa0070/n8nautomtion
          git push origin main
